
[dungeons]

	[dungeons.healer]
		wish = true

	[dungeons.devices]
		ss = true
		i4 = true

	[dungeons.heal_and_tonk]
		wish = false
		tank_ult = false

	[dungeons.tank]
		tank_ult = true

	[dungeons.qol]
		blood_ready = true
		blood_done = true
		auto_potion = true

[dungeon]

	[dungeon.devices]
		i4 = false

